<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="width" value="0.02" />   <!-- Beams are square in length and width -->
  <xacro:property name="height1" value="0.1" />   <!-- Link 1 -->
  <xacro:property name="height2" value="0.25" />   <!-- Link 2 -->
  <xacro:property name="axle_offset" value="0.01" /> <!-- Space between joint and end of beam -->
  <xacro:property name="damp" value="0.2" />    <!-- damping coefficient -->

  <!-- Default Inertial -->
  <xacro:macro name="default_inertial" params="z_value i_value mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${i_value}" ixy="0.0" ixz="0.0"
               iyy="${i_value}" iyz="0.0"
               izz="${i_value}" />
      </inertial>
  </xacro:macro>

  <!-- Import Gazebo elements, including Gazebo colors -->
  <xacro:include filename="$(find rrbot)/urdf/rrbot.gazebo" />
  
  <!-- Joint between Plate Link and Mid Link -->
  <joint name="joint_plate_arm" type="fixed">
    <parent link="mid_link"/>
    <child link="plate_link"/>
    <origin xyz="0 0 ${height2 - axle_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <dynamics damping="${damp}"/>
    <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14" />
  </joint>

  <!-- Plate Link -->
  <link name="plate_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <cylinder length="0.01" radius="0.2"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	      <cylinder length="0.01" radius="0.2"/>
      </geometry>
    </collision>

    <xacro:default_inertial z_value="1" i_value="1.0" mass="0.1"/>
  </link> 

  <!-- Joint between Base link and Arm link -->
 	<joint name="joint_base_arm" type="fixed">
    <parent link="base_link"/>
    <child link="arm_link"/>
    <origin xyz="-0.14 0 0.1" rpy="0 0 0"/>
	</joint> 

  <!-- Arm Link -->
  <link name="arm_link">
    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
				<cylinder length="${height1}" radius="${width}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
				<cylinder length="${height1}" radius="${width}"/>
      </geometry>
    </collision>

    <xacro:default_inertial z_value="${height1/2}" i_value="1.0" mass="0.1"/>
  </link>

  <!-- Joint between Base Link and Middle Link -->
  <joint name="joint_base_mid" type="prismatic">
    <parent link="arm_link"/>
    <child link="mid_link"/>
    <origin xyz="0 0 ${height1 - axle_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damp}"/>
    <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14" />
  </joint>

  <!-- Middle Link -->
  <link name="mid_link">
    <visual>
      <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height2}" radius="${width - axle_offset}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height2}" radius="${width - axle_offset}"/>
      </geometry>
    </collision>

    <xacro:default_inertial z_value="${height2/2 - axle_offset}" i_value="1.0" mass="0.1"/>
  </link>

 
  <transmission name="transmission1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_base_mid">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
 
</robot>